import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { Table, TableHeader, TableRow, TableCell, TableBody } from "@/components/pdf/table/table";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface CCODailyReturnFormIData {
  mineName: string;
  ownerCompany: string;
  reportDate: string;
  productionItems: { mineral: string; quantityMT: number; remarks: string }[];
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const CCODailyReturnFormIContent = ({ data }: { data: CCODailyReturnFormIData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`CCO Daily Return Form I - ${data.mineName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="FORM I - DAILY RETURN OF PRODUCTION" 
          subtitle="Coal Controller's Organization (CCO)" 
        />
        
        <Text style={styles.title}>Daily Production Return for {data.reportDate}</Text>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Mine Identification</Text>
          <KeyValue 
            items={[
              { key: "Name of Mine", value: data.mineName, valueStyle: styles.highlightedField },
              { key: "Owner Company", value: data.ownerCompany, valueStyle: styles.highlightedField },
              { key: "Date of Reporting", value: data.reportDate }
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Production Details</Text>
          <Table>
            <TableHeader>
              <TableRow header>
                <TableCell>Mineral</TableCell>
                <TableCell align="right">Quantity (Metric Tonnes)</TableCell>
                <TableCell>Remarks</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.productionItems.map((item, i) => (
                <TableRow key={i}>
                  <TableCell>{item.mineral}</TableCell>
                  <TableCell align="right" style={styles.highlightedField}>{item.quantityMT.toLocaleString()}</TableCell>
                  <TableCell>{item.remarks}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>3. Declaration</Text>
          <Text>
            I certify that the information given above is true and correct to the best of my knowledge and belief.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Mine Manager"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const CCODailyReturnFormI = ({ data }: { data: CCODailyReturnFormIData }) => (
  <PdfcnThemeProvider>
    <CCODailyReturnFormIContent data={data} />
  </PdfcnThemeProvider>
);
