import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { Table, TableHeader, TableRow, TableCell, TableBody } from "@/components/pdf/table/table";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface CLRAFormXIIData {
  mineName: string;
  contractorName: string;
  principalEmployer: string;
  reportingPeriod: { start: string; end: string };
  totalContractWorkers: number;
  wagesPaid: number;
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const CLRAFormXIIContent = ({ data }: { data: CLRAFormXIIData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`CLRA Form XII - ${data.contractorName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="FORM XII - REGISTER OF CONTRACTORS" 
          subtitle="Contract Labour (Regulation & Abolition) Act, 1970" 
        />
        
        <Text style={styles.title}>Register for Period: {data.reportingPeriod.start} to {data.reportingPeriod.end}</Text>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Establishment Details</Text>
          <KeyValue 
            items={[
              { key: "Principal Employer", value: data.principalEmployer, valueStyle: styles.highlightedField },
              { key: "Name of Mine/Establishment", value: data.mineName, valueStyle: styles.highlightedField },
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Contractor Details</Text>
          <Table>
            <TableHeader>
              <TableRow header>
                <TableCell>Name of Contractor</TableCell>
                <TableCell align="right">Total Workers Employed</TableCell>
                <TableCell align="right">Total Wages Paid (₹)</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>{data.contractorName}</TableCell>
                <TableCell align="right" style={styles.highlightedField}>{data.totalContractWorkers.toLocaleString()}</TableCell>
                <TableCell align="right" style={styles.highlightedField}>{data.wagesPaid.toLocaleString()}</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>3. Declaration</Text>
          <Text>
            I certify that the information given above is true and correct to the best of my knowledge and belief.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Principal Employer / Authorized Signatory"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const CLRAFormXII = ({ data }: { data: CLRAFormXIIData }) => (
  <PdfcnThemeProvider>
    <CLRAFormXIIContent data={data} />
  </PdfcnThemeProvider>
);
