import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { Table, TableHeader, TableRow, TableCell, TableBody } from "@/components/pdf/table/table";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface ECHalfYearlyReportData {
  mineName: string;
  ownerCompany: string;
  reportingPeriod: { start: string; end: string };
  environmentalClearanceNo: string;
  complianceStatus: { condition: string; status: string; remarks: string }[];
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const ECHalfYearlyReportContent = ({ data }: { data: ECHalfYearlyReportData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`EC Half-Yearly Report - ${data.mineName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="ENVIRONMENTAL CLEARANCE COMPLIANCE REPORT" 
          subtitle="Half-Yearly Compliance Report to MoEF&CC" 
        />
        
        <Text style={styles.title}>Report for Period: {data.reportingPeriod.start} to {data.reportingPeriod.end}</Text>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Mine Identification</Text>
          <KeyValue 
            items={[
              { key: "Name of Mine", value: data.mineName, valueStyle: styles.highlightedField },
              { key: "Owner Company", value: data.ownerCompany, valueStyle: styles.highlightedField },
              { key: "EC Letter No.", value: data.environmentalClearanceNo }
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Compliance Status of EC Conditions</Text>
          <Table>
            <TableHeader>
              <TableRow header>
                <TableCell>Condition</TableCell>
                <TableCell>Compliance Status</TableCell>
                <TableCell>Remarks</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.complianceStatus.map((item, i) => (
                <TableRow key={i}>
                  <TableCell>{item.condition}</TableCell>
                  <TableCell style={styles.highlightedField}>{item.status}</TableCell>
                  <TableCell>{item.remarks}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>3. Declaration</Text>
          <Text>
            I certify that the information given above is true and correct and that the project complies with all stipulated environmental conditions.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Mine Manager / Authorized Signatory"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const ECHalfYearlyReport = ({ data }: { data: ECHalfYearlyReportData }) => (
  <PdfcnThemeProvider>
    <ECHalfYearlyReportContent data={data} />
  </PdfcnThemeProvider>
);
