import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface Form4AData {
  mineName: string;
  ownerCompany: string;
  accidentDate: string;
  accidentTime: string;
  locationDetails: string;
  description: string;
  casualties: { name: string; age: number; designation: string; injuryNature: string }[];
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const Form4AContent = ({ data }: { data: Form4AData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`Form IV-A Accident Notice - ${data.mineName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="FORM IV-A - NOTICE OF ACCIDENT" 
          subtitle="See Regulation 9(1) of Metalliferous Mines Regulations, 1961" 
        />

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Mine Identification</Text>
          <KeyValue 
            items={[
              { key: "Name of Mine", value: data.mineName, valueStyle: styles.highlightedField },
              { key: "Owner Company", value: data.ownerCompany, valueStyle: styles.highlightedField },
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Accident Details</Text>
          <KeyValue 
            items={[
              { key: "Date of Accident", value: data.accidentDate, valueStyle: styles.highlightedField },
              { key: "Time of Accident", value: data.accidentTime, valueStyle: styles.highlightedField },
              { key: "Location", value: data.locationDetails, valueStyle: styles.highlightedField }
            ]} 
          />
          <Text style={{ marginTop: 10, fontWeight: 'bold' }}>Description of Accident:</Text>
          <Text style={styles.highlightedField}>{data.description}</Text>
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>3. Casualties</Text>
          {data.casualties.map((c, i) => (
            <View key={i} style={{ marginBottom: 10, padding: 10, borderWidth: 1, borderColor: theme.colors.border }}>
              <KeyValue 
                items={[
                  { key: "Name", value: c.name },
                  { key: "Age", value: c.age.toString() },
                  { key: "Designation", value: c.designation },
                  { key: "Nature of Injury", value: c.injuryNature }
                ]} 
              />
            </View>
          ))}
          {data.casualties.length === 0 && <Text>No casualties reported.</Text>}
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>4. Declaration</Text>
          <Text>
            I certify that the information given above is true and correct to the best of my knowledge and belief.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Mine Manager"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const Form4AAccidentNotice = ({ data }: { data: Form4AData }) => (
  <PdfcnThemeProvider>
    <Form4AContent data={data} />
  </PdfcnThemeProvider>
);
