import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { Table, TableHeader, TableRow, TableCell, TableBody } from "@/components/pdf/table/table";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface Form4BData {
  mineName: string;
  ownerCompany: string;
  reportingYear: string;
  accidents: { date: string; time: string; location: string; description: string; casualties: number }[];
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const Form4BContent = ({ data }: { data: Form4BData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`Form IV-B Accident Register - ${data.mineName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="FORM IV-B - REGISTER OF ACCIDENTS" 
          subtitle="See Regulation 9(4) of Metalliferous Mines Regulations, 1961" 
        />
        
        <Text style={styles.title}>Register of Accidents for the year {data.reportingYear}</Text>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Mine Identification</Text>
          <KeyValue 
            items={[
              { key: "Name of Mine", value: data.mineName, valueStyle: styles.highlightedField },
              { key: "Owner Company", value: data.ownerCompany, valueStyle: styles.highlightedField },
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Accidents Log</Text>
          <Table>
            <TableHeader>
              <TableRow header>
                <TableCell>Date</TableCell>
                <TableCell>Time</TableCell>
                <TableCell>Location</TableCell>
                <TableCell>Description</TableCell>
                <TableCell align="right">Casualties</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.accidents.map((a, i) => (
                <TableRow key={i}>
                  <TableCell>{a.date}</TableCell>
                  <TableCell>{a.time}</TableCell>
                  <TableCell>{a.location}</TableCell>
                  <TableCell>{a.description}</TableCell>
                  <TableCell align="right">{a.casualties.toString()}</TableCell>
                </TableRow>
              ))}
              {data.accidents.length === 0 && (
                <TableRow>
                  <TableCell>No accidents recorded</TableCell>
                  <TableCell></TableCell>
                  <TableCell></TableCell>
                  <TableCell></TableCell>
                  <TableCell></TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>3. Declaration</Text>
          <Text>
            I certify that the information given above is true and correct to the best of my knowledge and belief.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Mine Manager"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const Form4BAccidentRegister = ({ data }: { data: Form4BData }) => (
  <PdfcnThemeProvider>
    <Form4BContent data={data} />
  </PdfcnThemeProvider>
);
