import React from 'react';
import { View, StyleSheet, Document, Page } from "@/lib/pdf-primitives";
import { Text } from "@/components/pdf/text/text";
import { Section } from "@/components/pdf/section/section";
import { KeyValue } from "@/components/pdf/key-value/key-value";
import { PageHeader } from "@/components/pdf/page-header/page-header";
import { PageFooter } from "@/components/pdf/page-footer/page-footer";
import { Signature } from "@/components/pdf/signature/signature";
import { Table, TableHeader, TableRow, TableCell, TableBody } from "@/components/pdf/table/table";
import { PdfcnThemeProvider, usePdfcnTheme } from "@/components/pdf/theme-provider";

export interface SafetyCommitteeMinutesData {
  mineName: string;
  ownerCompany: string;
  meetingDate: string;
  meetingTime: string;
  location: string;
  attendees: string[];
  agendaItems: { topic: string; discussion: string; actionItem: string; responsible: string }[];
  managerName: string;
  signatureDataUrl?: string;
  signedAt?: string;
}

const SafetyCommitteeMinutesContent = ({ data }: { data: SafetyCommitteeMinutesData }) => {
  const theme = usePdfcnTheme();

  const styles = StyleSheet.create({
    page: {
      backgroundColor: theme.colors.background,
      boxSizing: "border-box",
      padding: theme.spacing.page.marginTop,
      paddingBottom: theme.spacing.page.marginBottom,
      position: "relative",
    },
    highlightedField: {
      backgroundColor: 'rgba(252, 213, 53, 0.2)', // COMET highlightAmber
      borderRadius: 4,
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.colors.primary,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      borderBottomStyle: 'solid',
      paddingBottom: 4,
      marginBottom: 10,
    }
  });

  return (
    <Document title={`Safety Committee Minutes - ${data.mineName}`}>
      <Page size="A4" style={styles.page}>
        <PageHeader 
          title="SAFETY COMMITTEE MEETING MINUTES" 
          subtitle="Statutory Record - Mines Act 1952" 
        />
        
        <Text style={styles.title}>Minutes of Meeting held on {data.meetingDate}</Text>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>1. Meeting Details</Text>
          <KeyValue 
            items={[
              { key: "Name of Mine", value: data.mineName, valueStyle: styles.highlightedField },
              { key: "Owner Company", value: data.ownerCompany, valueStyle: styles.highlightedField },
              { key: "Date & Time", value: `${data.meetingDate} at ${data.meetingTime}` },
              { key: "Location", value: data.location }
            ]} 
          />
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>2. Attendees</Text>
          <Text>{data.attendees.join(', ')}</Text>
        </Section>

        <Section style={{ marginBottom: 20 }}>
          <Text style={styles.sectionTitle}>3. Agenda & Minutes</Text>
          <Table>
            <TableHeader>
              <TableRow header>
                <TableCell>Topic</TableCell>
                <TableCell>Discussion</TableCell>
                <TableCell>Action Item</TableCell>
                <TableCell>Responsible</TableCell>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.agendaItems.map((item, i) => (
                <TableRow key={i}>
                  <TableCell>{item.topic}</TableCell>
                  <TableCell>{item.discussion}</TableCell>
                  <TableCell style={styles.highlightedField}>{item.actionItem}</TableCell>
                  <TableCell>{item.responsible}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Section>

        <Section noWrap style={{ marginTop: 40 }}>
          <Text style={styles.sectionTitle}>4. Sign-off</Text>
          <Text>
            I certify that these minutes accurately reflect the proceedings of the Safety Committee Meeting.
          </Text>
          
          <View style={{ marginTop: 30, flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Signature 
              name={data.managerName}
              title="Chairman / Mine Manager"
              date={data.signedAt || "Draft (Unsigned)"}
              signatureImage={data.signatureDataUrl}
            />
          </View>
        </Section>

        <PageFooter 
          leftText={`Generated by COMET Compliance Platform`} 
          rightText="Page 1 of 1"
          sticky 
        />
      </Page>
    </Document>
  );
};

export const SafetyCommitteeMinutes = ({ data }: { data: SafetyCommitteeMinutesData }) => (
  <PdfcnThemeProvider>
    <SafetyCommitteeMinutesContent data={data} />
  </PdfcnThemeProvider>
);
