/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedOcrRouteImport } from './routes/_authenticated/ocr'
import { Route as AuthenticatedMobileInspectionRouteImport } from './routes/_authenticated/mobile-inspection'
import { Route as AuthenticatedMineMapRouteImport } from './routes/_authenticated/mine-map'
import { Route as AuthenticatedMineManagerRouteImport } from './routes/_authenticated/mine-manager'
import { Route as AuthenticatedGrievancesRouteImport } from './routes/_authenticated/grievances'
import { Route as AuthenticatedEnvironmentRouteImport } from './routes/_authenticated/environment'
import { Route as AuthenticatedCorporateDashboardRouteImport } from './routes/_authenticated/corporate-dashboard'
import { Route as AuthenticatedContractorsRouteImport } from './routes/_authenticated/contractors'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAiAnalyticsRouteImport } from './routes/_authenticated/ai-analytics'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedInspectionIndexRouteImport } from './routes/_authenticated/inspection/index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedViolationsIdRouteImport } from './routes/_authenticated/violations/$id'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedInspectionIdRouteImport } from './routes/_authenticated/inspection/$id'
import { Route as AuthenticatedIncidentsIdRouteImport } from './routes/_authenticated/incidents/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCorrectiveActionsIdRouteImport } from './routes/_authenticated/corrective-actions/$id'
import { Route as AuthenticatedComplianceInstanceIdRouteImport } from './routes/_authenticated/compliance/$instanceId'
import { Route as AuthenticatedComplianceIdRouteImport } from './routes/_authenticated/compliance/$id'
import { Route as AuthenticatedComplianceMineIdIndexRouteImport } from './routes/_authenticated/compliance/$mineId/index'
import { Route as AuthenticatedAdminMinesIndexRouteImport } from './routes/_authenticated/admin/mines/index'
import { Route as AuthenticatedComplianceMineIdInstanceIdRouteImport } from './routes/_authenticated/compliance/$mineId/$instanceId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcrRoute = AuthenticatedOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileInspectionRoute =
  AuthenticatedMobileInspectionRouteImport.update({
    id: '/mobile-inspection',
    path: '/mobile-inspection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMineMapRoute = AuthenticatedMineMapRouteImport.update({
  id: '/mine-map',
  path: '/mine-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineManagerRoute =
  AuthenticatedMineManagerRouteImport.update({
    id: '/mine-manager',
    path: '/mine-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrievancesRoute = AuthenticatedGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnvironmentRoute =
  AuthenticatedEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorporateDashboardRoute =
  AuthenticatedCorporateDashboardRouteImport.update({
    id: '/corporate-dashboard',
    path: '/corporate-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractorsRoute =
  AuthenticatedContractorsRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAnalyticsRoute =
  AuthenticatedAiAnalyticsRouteImport.update({
    id: '/ai-analytics',
    path: '/ai-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIndexRoute =
  AuthenticatedInspectionIndexRouteImport.update({
    id: '/inspection/',
    path: '/inspection/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViolationsIdRoute =
  AuthenticatedViolationsIdRouteImport.update({
    id: '/violations/$id',
    path: '/violations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedInspectionIdRoute =
  AuthenticatedInspectionIdRouteImport.update({
    id: '/inspection/$id',
    path: '/inspection/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIdRoute =
  AuthenticatedIncidentsIdRouteImport.update({
    id: '/incidents/$id',
    path: '/incidents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorrectiveActionsIdRoute =
  AuthenticatedCorrectiveActionsIdRouteImport.update({
    id: '/corrective-actions/$id',
    path: '/corrective-actions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceInstanceIdRoute =
  AuthenticatedComplianceInstanceIdRouteImport.update({
    id: '/compliance/$instanceId',
    path: '/compliance/$instanceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceIdRoute =
  AuthenticatedComplianceIdRouteImport.update({
    id: '/compliance/$id',
    path: '/compliance/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceMineIdIndexRoute =
  AuthenticatedComplianceMineIdIndexRouteImport.update({
    id: '/compliance/$mineId/',
    path: '/compliance/$mineId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMinesIndexRoute =
  AuthenticatedAdminMinesIndexRouteImport.update({
    id: '/admin/mines/',
    path: '/admin/mines/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceMineIdInstanceIdRoute =
  AuthenticatedComplianceMineIdInstanceIdRouteImport.update({
    id: '/compliance/$mineId/$instanceId',
    path: '/compliance/$mineId/$instanceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/corporate-dashboard': typeof AuthenticatedCorporateDashboardRoute
  '/environment': typeof AuthenticatedEnvironmentRoute
  '/grievances': typeof AuthenticatedGrievancesRoute
  '/mine-manager': typeof AuthenticatedMineManagerRoute
  '/mine-map': typeof AuthenticatedMineMapRoute
  '/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/ocr': typeof AuthenticatedOcrRoute
  '/production': typeof AuthenticatedProductionRoute
  '/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/compliance/$instanceId': typeof AuthenticatedComplianceInstanceIdRoute
  '/corrective-actions/$id': typeof AuthenticatedCorrectiveActionsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/inspection/$id': typeof AuthenticatedInspectionIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/violations/$id': typeof AuthenticatedViolationsIdRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/inspection/': typeof AuthenticatedInspectionIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/compliance/$mineId/$instanceId': typeof AuthenticatedComplianceMineIdInstanceIdRoute
  '/admin/mines/': typeof AuthenticatedAdminMinesIndexRoute
  '/compliance/$mineId/': typeof AuthenticatedComplianceMineIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/contractors': typeof AuthenticatedContractorsRoute
  '/corporate-dashboard': typeof AuthenticatedCorporateDashboardRoute
  '/environment': typeof AuthenticatedEnvironmentRoute
  '/grievances': typeof AuthenticatedGrievancesRoute
  '/mine-manager': typeof AuthenticatedMineManagerRoute
  '/mine-map': typeof AuthenticatedMineMapRoute
  '/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/ocr': typeof AuthenticatedOcrRoute
  '/production': typeof AuthenticatedProductionRoute
  '/': typeof AuthenticatedIndexRoute
  '/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/compliance/$instanceId': typeof AuthenticatedComplianceInstanceIdRoute
  '/corrective-actions/$id': typeof AuthenticatedCorrectiveActionsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/inspection/$id': typeof AuthenticatedInspectionIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/violations/$id': typeof AuthenticatedViolationsIdRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/inspection': typeof AuthenticatedInspectionIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/compliance/$mineId/$instanceId': typeof AuthenticatedComplianceMineIdInstanceIdRoute
  '/admin/mines': typeof AuthenticatedAdminMinesIndexRoute
  '/compliance/$mineId': typeof AuthenticatedComplianceMineIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/ai-analytics': typeof AuthenticatedAiAnalyticsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/contractors': typeof AuthenticatedContractorsRoute
  '/_authenticated/corporate-dashboard': typeof AuthenticatedCorporateDashboardRoute
  '/_authenticated/environment': typeof AuthenticatedEnvironmentRoute
  '/_authenticated/grievances': typeof AuthenticatedGrievancesRoute
  '/_authenticated/mine-manager': typeof AuthenticatedMineManagerRoute
  '/_authenticated/mine-map': typeof AuthenticatedMineMapRoute
  '/_authenticated/mobile-inspection': typeof AuthenticatedMobileInspectionRoute
  '/_authenticated/ocr': typeof AuthenticatedOcrRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/compliance/$id': typeof AuthenticatedComplianceIdRoute
  '/_authenticated/compliance/$instanceId': typeof AuthenticatedComplianceInstanceIdRoute
  '/_authenticated/corrective-actions/$id': typeof AuthenticatedCorrectiveActionsIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/_authenticated/inspection/$id': typeof AuthenticatedInspectionIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/violations/$id': typeof AuthenticatedViolationsIdRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/inspection/': typeof AuthenticatedInspectionIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/compliance/$mineId/$instanceId': typeof AuthenticatedComplianceMineIdInstanceIdRoute
  '/_authenticated/admin/mines/': typeof AuthenticatedAdminMinesIndexRoute
  '/_authenticated/compliance/$mineId/': typeof AuthenticatedComplianceMineIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai-analytics'
    | '/alerts'
    | '/contractors'
    | '/corporate-dashboard'
    | '/environment'
    | '/grievances'
    | '/mine-manager'
    | '/mine-map'
    | '/mobile-inspection'
    | '/ocr'
    | '/production'
    | '/compliance/$id'
    | '/compliance/$instanceId'
    | '/corrective-actions/$id'
    | '/errors/$error'
    | '/incidents/$id'
    | '/inspection/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/violations/$id'
    | '/apps/'
    | '/compliance/'
    | '/incidents/'
    | '/inspection/'
    | '/reports/'
    | '/settings/'
    | '/users/'
    | '/compliance/$mineId/$instanceId'
    | '/admin/mines/'
    | '/compliance/$mineId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ai-analytics'
    | '/alerts'
    | '/contractors'
    | '/corporate-dashboard'
    | '/environment'
    | '/grievances'
    | '/mine-manager'
    | '/mine-map'
    | '/mobile-inspection'
    | '/ocr'
    | '/production'
    | '/'
    | '/compliance/$id'
    | '/compliance/$instanceId'
    | '/corrective-actions/$id'
    | '/errors/$error'
    | '/incidents/$id'
    | '/inspection/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/violations/$id'
    | '/apps'
    | '/compliance'
    | '/incidents'
    | '/inspection'
    | '/reports'
    | '/settings'
    | '/users'
    | '/compliance/$mineId/$instanceId'
    | '/admin/mines'
    | '/compliance/$mineId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/ai-analytics'
    | '/_authenticated/alerts'
    | '/_authenticated/contractors'
    | '/_authenticated/corporate-dashboard'
    | '/_authenticated/environment'
    | '/_authenticated/grievances'
    | '/_authenticated/mine-manager'
    | '/_authenticated/mine-map'
    | '/_authenticated/mobile-inspection'
    | '/_authenticated/ocr'
    | '/_authenticated/production'
    | '/_authenticated/'
    | '/_authenticated/compliance/$id'
    | '/_authenticated/compliance/$instanceId'
    | '/_authenticated/corrective-actions/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/incidents/$id'
    | '/_authenticated/inspection/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/violations/$id'
    | '/_authenticated/apps/'
    | '/_authenticated/compliance/'
    | '/_authenticated/incidents/'
    | '/_authenticated/inspection/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/compliance/$mineId/$instanceId'
    | '/_authenticated/admin/mines/'
    | '/_authenticated/compliance/$mineId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocr': {
      id: '/_authenticated/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof AuthenticatedOcrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-inspection': {
      id: '/_authenticated/mobile-inspection'
      path: '/mobile-inspection'
      fullPath: '/mobile-inspection'
      preLoaderRoute: typeof AuthenticatedMobileInspectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-map': {
      id: '/_authenticated/mine-map'
      path: '/mine-map'
      fullPath: '/mine-map'
      preLoaderRoute: typeof AuthenticatedMineMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine-manager': {
      id: '/_authenticated/mine-manager'
      path: '/mine-manager'
      fullPath: '/mine-manager'
      preLoaderRoute: typeof AuthenticatedMineManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grievances': {
      id: '/_authenticated/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof AuthenticatedGrievancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/environment': {
      id: '/_authenticated/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof AuthenticatedEnvironmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corporate-dashboard': {
      id: '/_authenticated/corporate-dashboard'
      path: '/corporate-dashboard'
      fullPath: '/corporate-dashboard'
      preLoaderRoute: typeof AuthenticatedCorporateDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractors': {
      id: '/_authenticated/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof AuthenticatedContractorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-analytics': {
      id: '/_authenticated/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof AuthenticatedAiAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/': {
      id: '/_authenticated/inspection/'
      path: '/inspection'
      fullPath: '/inspection/'
      preLoaderRoute: typeof AuthenticatedInspectionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/violations/$id': {
      id: '/_authenticated/violations/$id'
      path: '/violations/$id'
      fullPath: '/violations/$id'
      preLoaderRoute: typeof AuthenticatedViolationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/inspection/$id': {
      id: '/_authenticated/inspection/$id'
      path: '/inspection/$id'
      fullPath: '/inspection/$id'
      preLoaderRoute: typeof AuthenticatedInspectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/$id': {
      id: '/_authenticated/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corrective-actions/$id': {
      id: '/_authenticated/corrective-actions/$id'
      path: '/corrective-actions/$id'
      fullPath: '/corrective-actions/$id'
      preLoaderRoute: typeof AuthenticatedCorrectiveActionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/$instanceId': {
      id: '/_authenticated/compliance/$instanceId'
      path: '/compliance/$instanceId'
      fullPath: '/compliance/$instanceId'
      preLoaderRoute: typeof AuthenticatedComplianceInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/$id': {
      id: '/_authenticated/compliance/$id'
      path: '/compliance/$id'
      fullPath: '/compliance/$id'
      preLoaderRoute: typeof AuthenticatedComplianceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/$mineId/': {
      id: '/_authenticated/compliance/$mineId/'
      path: '/compliance/$mineId'
      fullPath: '/compliance/$mineId/'
      preLoaderRoute: typeof AuthenticatedComplianceMineIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mines/': {
      id: '/_authenticated/admin/mines/'
      path: '/admin/mines'
      fullPath: '/admin/mines/'
      preLoaderRoute: typeof AuthenticatedAdminMinesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/$mineId/$instanceId': {
      id: '/_authenticated/compliance/$mineId/$instanceId'
      path: '/compliance/$mineId/$instanceId'
      fullPath: '/compliance/$mineId/$instanceId'
      preLoaderRoute: typeof AuthenticatedComplianceMineIdInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAiAnalyticsRoute: typeof AuthenticatedAiAnalyticsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedContractorsRoute: typeof AuthenticatedContractorsRoute
  AuthenticatedCorporateDashboardRoute: typeof AuthenticatedCorporateDashboardRoute
  AuthenticatedEnvironmentRoute: typeof AuthenticatedEnvironmentRoute
  AuthenticatedGrievancesRoute: typeof AuthenticatedGrievancesRoute
  AuthenticatedMineManagerRoute: typeof AuthenticatedMineManagerRoute
  AuthenticatedMineMapRoute: typeof AuthenticatedMineMapRoute
  AuthenticatedMobileInspectionRoute: typeof AuthenticatedMobileInspectionRoute
  AuthenticatedOcrRoute: typeof AuthenticatedOcrRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComplianceIdRoute: typeof AuthenticatedComplianceIdRoute
  AuthenticatedComplianceInstanceIdRoute: typeof AuthenticatedComplianceInstanceIdRoute
  AuthenticatedCorrectiveActionsIdRoute: typeof AuthenticatedCorrectiveActionsIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedIncidentsIdRoute: typeof AuthenticatedIncidentsIdRoute
  AuthenticatedInspectionIdRoute: typeof AuthenticatedInspectionIdRoute
  AuthenticatedViolationsIdRoute: typeof AuthenticatedViolationsIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
  AuthenticatedInspectionIndexRoute: typeof AuthenticatedInspectionIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedComplianceMineIdInstanceIdRoute: typeof AuthenticatedComplianceMineIdInstanceIdRoute
  AuthenticatedAdminMinesIndexRoute: typeof AuthenticatedAdminMinesIndexRoute
  AuthenticatedComplianceMineIdIndexRoute: typeof AuthenticatedComplianceMineIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAiAnalyticsRoute: AuthenticatedAiAnalyticsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedContractorsRoute: AuthenticatedContractorsRoute,
  AuthenticatedCorporateDashboardRoute: AuthenticatedCorporateDashboardRoute,
  AuthenticatedEnvironmentRoute: AuthenticatedEnvironmentRoute,
  AuthenticatedGrievancesRoute: AuthenticatedGrievancesRoute,
  AuthenticatedMineManagerRoute: AuthenticatedMineManagerRoute,
  AuthenticatedMineMapRoute: AuthenticatedMineMapRoute,
  AuthenticatedMobileInspectionRoute: AuthenticatedMobileInspectionRoute,
  AuthenticatedOcrRoute: AuthenticatedOcrRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComplianceIdRoute: AuthenticatedComplianceIdRoute,
  AuthenticatedComplianceInstanceIdRoute:
    AuthenticatedComplianceInstanceIdRoute,
  AuthenticatedCorrectiveActionsIdRoute: AuthenticatedCorrectiveActionsIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedIncidentsIdRoute: AuthenticatedIncidentsIdRoute,
  AuthenticatedInspectionIdRoute: AuthenticatedInspectionIdRoute,
  AuthenticatedViolationsIdRoute: AuthenticatedViolationsIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  AuthenticatedInspectionIndexRoute: AuthenticatedInspectionIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedComplianceMineIdInstanceIdRoute:
    AuthenticatedComplianceMineIdInstanceIdRoute,
  AuthenticatedAdminMinesIndexRoute: AuthenticatedAdminMinesIndexRoute,
  AuthenticatedComplianceMineIdIndexRoute:
    AuthenticatedComplianceMineIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
