-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subsidiaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code character varying NOT NULL UNIQUE,
  state text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subsidiaries_pkey PRIMARY KEY (id),
  CONSTRAINT subsidiaries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.mines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subsidiary_id uuid NOT NULL,
  name text NOT NULL,
  mine_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::mine_status_enum,
  boundary_geojson jsonb,
  district text,
  state text,
  dgms_region text,
  ec_number text,
  coal_grade text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mines_pkey PRIMARY KEY (id),
  CONSTRAINT mines_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  keycloak_subject text UNIQUE,
  full_name text NOT NULL,
  designation text,
  email text,
  mine_id uuid,
  subsidiary_id uuid,
  preferred_language text DEFAULT 'en'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT users_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name USER-DEFINED NOT NULL UNIQUE,
  scope_level USER-DEFINED NOT NULL,
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_roles (
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.regulations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text UNIQUE,
  title text NOT NULL,
  statute text,
  section_reference text,
  category USER-DEFINED NOT NULL,
  description text,
  authority USER-DEFINED,
  consequence_of_non_compliance text,
  version integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT regulations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.compliance_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  regulation_id uuid NOT NULL,
  title text NOT NULL,
  recurrence USER-DEFINED NOT NULL,
  grace_period_days integer DEFAULT 0,
  reminder_offsets_days ARRAY DEFAULT ARRAY[30, 7, 1],
  applicable_mine_types ARRAY NOT NULL,
  applicable_states ARRAY,
  documents_required ARRAY,
  responsible_role USER-DEFINED,
  regulation_version integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT compliance_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_requirements_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.regulations(id)
);
CREATE TABLE public.compliance_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  due_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::instance_status,
  is_late_submission boolean DEFAULT false,
  assigned_to uuid,
  submitted_by uuid,
  submitted_at timestamp with time zone,
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  regulation_version integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  submitted_to_authority_at timestamp with time zone,
  submission_reference_number character varying,
  submitted_to_authority_by uuid,
  notes text,
  CONSTRAINT compliance_instances_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_instances_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.compliance_requirements(id),
  CONSTRAINT compliance_instances_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT compliance_instances_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT compliance_instances_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT compliance_instances_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.users(id),
  CONSTRAINT compliance_instances_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT compliance_instances_submitted_to_authority_by_fkey FOREIGN KEY (submitted_to_authority_by) REFERENCES public.users(id)
);
CREATE TABLE public.compliance_evidences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  instance_id uuid NOT NULL,
  document_url text NOT NULL,
  file_name text,
  file_type text,
  file_size_bytes integer,
  upload_method USER-DEFINED NOT NULL,
  ocr_result_id uuid,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  uploaded_by uuid,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT compliance_evidences_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_evidences_instance_id_fkey FOREIGN KEY (instance_id) REFERENCES public.compliance_instances(id),
  CONSTRAINT compliance_evidences_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT compliance_evidences_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT fk_ce_ocr FOREIGN KEY (ocr_result_id) REFERENCES public.ocr_extraction_results(id)
);
CREATE TABLE public.inspection_checklist_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  inspection_type USER-DEFINED NOT NULL,
  applicable_mine_types ARRAY NOT NULL,
  regulation_reference text,
  checklist_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  version integer NOT NULL DEFAULT 1,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inspection_checklist_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inspections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  conducted_by uuid NOT NULL,
  inspection_type USER-DEFINED NOT NULL,
  checklist_template_id uuid,
  zone text,
  geo_stamp jsonb,
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  submitted_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::inspection_status,
  sync_status USER-DEFINED DEFAULT 'pending_sync'::sync_status_enum,
  observation_count integer DEFAULT 0,
  violation_count integer DEFAULT 0,
  overall_remarks text,
  inspection_memo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inspections_pkey PRIMARY KEY (id),
  CONSTRAINT inspections_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT inspections_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT inspections_conducted_by_fkey FOREIGN KEY (conducted_by) REFERENCES public.users(id),
  CONSTRAINT inspections_checklist_template_id_fkey FOREIGN KEY (checklist_template_id) REFERENCES public.inspection_checklist_templates(id)
);
CREATE TABLE public.observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inspection_id uuid NOT NULL,
  checklist_item_id text,
  category text NOT NULL,
  description text NOT NULL,
  severity USER-DEFINED NOT NULL,
  status USER-DEFINED,
  geo_stamp jsonb,
  voice_note_url text,
  voice_transcription text,
  ai_category text,
  ai_confidence_score numeric,
  violation_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ai_auto_applied boolean DEFAULT false,
  ai_status character varying,
  CONSTRAINT observations_pkey PRIMARY KEY (id),
  CONSTRAINT observations_inspection_id_fkey FOREIGN KEY (inspection_id) REFERENCES public.inspections(id),
  CONSTRAINT fk_obs_violation FOREIGN KEY (violation_id) REFERENCES public.violations(id)
);
CREATE TABLE public.violations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  observation_id uuid NOT NULL,
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  statute_reference text,
  category USER-DEFINED,
  severity USER-DEFINED NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'reported'::violation_status,
  corrective_action_id uuid,
  reported_by uuid NOT NULL,
  reported_at timestamp with time zone DEFAULT now(),
  dismissed_reason text,
  is_regulator_visible boolean DEFAULT false,
  recurrence_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT violations_pkey PRIMARY KEY (id),
  CONSTRAINT violations_observation_id_fkey FOREIGN KEY (observation_id) REFERENCES public.observations(id),
  CONSTRAINT violations_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT violations_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT violations_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT fk_vio_capa FOREIGN KEY (corrective_action_id) REFERENCES public.corrective_actions(id)
);
CREATE TABLE public.corrective_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type USER-DEFINED NOT NULL,
  source_id uuid NOT NULL,
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  description text NOT NULL,
  preventive_measures text,
  assigned_to uuid NOT NULL,
  assigned_by uuid NOT NULL,
  due_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'assigned'::capa_status,
  completion_notes text,
  completed_at timestamp with time zone,
  verified_by uuid,
  verified_at timestamp with time zone,
  escalation_workflow_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  root_cause text,
  CONSTRAINT corrective_actions_pkey PRIMARY KEY (id),
  CONSTRAINT corrective_actions_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT corrective_actions_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT corrective_actions_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT corrective_actions_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT corrective_actions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT fk_capa_escalation FOREIGN KEY (escalation_workflow_id) REFERENCES public.escalation_workflow_instances(id)
);
CREATE TABLE public.media_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_type USER-DEFINED NOT NULL,
  parent_id uuid NOT NULL,
  media_type USER-DEFINED NOT NULL,
  file_url text NOT NULL,
  thumbnail_url text,
  file_size_bytes integer,
  mime_type text,
  geo_stamp jsonb,
  sync_status text DEFAULT 'pending_upload'::text,
  captured_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT media_attachments_captured_by_fkey FOREIGN KEY (captured_by) REFERENCES public.users(id)
);
CREATE TABLE public.monitoring_stations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  station_type USER-DEFINED NOT NULL,
  name text NOT NULL,
  location jsonb,
  is_iot_enabled boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monitoring_stations_pkey PRIMARY KEY (id),
  CONSTRAINT monitoring_stations_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id)
);
CREATE TABLE public.environment_readings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  station_id uuid NOT NULL,
  parameter USER-DEFINED NOT NULL,
  value numeric NOT NULL,
  unit text NOT NULL,
  recorded_at timestamp with time zone NOT NULL,
  source USER-DEFINED NOT NULL,
  ec_condition_ref text,
  prescribed_limit numeric,
  threshold_breached boolean DEFAULT false,
  breach_severity text,
  sensor_id text,
  recorded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT environment_readings_pkey PRIMARY KEY (id),
  CONSTRAINT environment_readings_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT environment_readings_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.monitoring_stations(id),
  CONSTRAINT environment_readings_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.production_readings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  reporting_date date NOT NULL,
  shift USER-DEFINED NOT NULL,
  quantity_tonnes numeric NOT NULL CHECK (quantity_tonnes >= 0::numeric),
  coal_grade text,
  seam_name text,
  source text NOT NULL,
  overburden_cum numeric,
  equipment_deployed jsonb,
  workforce_count integer,
  reported_by uuid NOT NULL,
  anomaly_flagged boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT production_readings_pkey PRIMARY KEY (id),
  CONSTRAINT production_readings_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT production_readings_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT production_readings_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id)
);
CREATE TABLE public.contractors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  registration_number text NOT NULL UNIQUE,
  pan character varying,
  gst_number text,
  contact_person text,
  contact_email text,
  address text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::contractor_status,
  blacklist_reason text,
  risk_rating USER-DEFINED,
  trust_score numeric,
  onboarded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contractor_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contractor_id uuid NOT NULL,
  doc_type USER-DEFINED NOT NULL,
  document_url text NOT NULL,
  ocr_result_id uuid,
  valid_from date NOT NULL,
  valid_until date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'valid'::contractor_doc_status,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractor_documents_pkey PRIMARY KEY (id),
  CONSTRAINT contractor_documents_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id),
  CONSTRAINT contractor_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id),
  CONSTRAINT contractor_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT fk_cd_ocr FOREIGN KEY (ocr_result_id) REFERENCES public.ocr_extraction_results(id)
);
CREATE TABLE public.contractor_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contractor_id uuid NOT NULL,
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  work_order_number text NOT NULL UNIQUE,
  scope_of_work text NOT NULL,
  work_zone text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  max_workers_permitted integer,
  status USER-DEFINED NOT NULL DEFAULT 'active'::assignment_status,
  blocked_reason text,
  performance_rating numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contractor_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT contractor_assignments_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id),
  CONSTRAINT contractor_assignments_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT contractor_assignments_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id)
);
CREATE TABLE public.contract_workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contractor_id uuid NOT NULL,
  name text NOT NULL,
  worker_id_card_number text NOT NULL,
  aadhaar_hash text,
  age integer,
  skill_category text,
  designation text,
  training_certificates jsonb DEFAULT '[]'::jsonb,
  esi_number text,
  epf_number text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_workers_pkey PRIMARY KEY (id),
  CONSTRAINT contract_workers_contractor_id_fkey FOREIGN KEY (contractor_id) REFERENCES public.contractors(id)
);
CREATE TABLE public.incident_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  incident_type USER-DEFINED NOT NULL,
  description text NOT NULL,
  severity USER-DEFINED NOT NULL,
  ai_suggested_severity USER-DEFINED,
  ai_suggested_category text,
  geo_stamp jsonb,
  zone text,
  shift USER-DEFINED,
  persons_involved jsonb DEFAULT '[]'::jsonb,
  voice_note_url text,
  voice_transcription text,
  immediate_actions_taken text,
  is_linked_to_accident_register boolean DEFAULT false,
  corrective_action_id uuid,
  reported_by uuid NOT NULL,
  reported_at timestamp with time zone DEFAULT now(),
  sync_status text DEFAULT 'pending_sync'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT incident_reports_pkey PRIMARY KEY (id),
  CONSTRAINT incident_reports_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT incident_reports_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT incident_reports_corrective_action_id_fkey FOREIGN KEY (corrective_action_id) REFERENCES public.corrective_actions(id),
  CONSTRAINT incident_reports_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id)
);
CREATE TABLE public.safety_observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  zone text NOT NULL,
  observation_type USER-DEFINED NOT NULL,
  category text,
  description text NOT NULL,
  geo_stamp jsonb,
  assigned_to uuid,
  status USER-DEFINED NOT NULL DEFAULT 'open'::safety_obs_status,
  corrected_at timestamp with time zone,
  correction_evidence_ids ARRAY DEFAULT ARRAY[]::uuid[],
  observed_by uuid NOT NULL,
  observed_at timestamp with time zone DEFAULT now(),
  sync_status text DEFAULT 'pending_sync'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT safety_observations_pkey PRIMARY KEY (id),
  CONSTRAINT safety_observations_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT safety_observations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT safety_observations_observed_by_fkey FOREIGN KEY (observed_by) REFERENCES public.users(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  priority USER-DEFINED NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  target_user_id uuid NOT NULL,
  target_role text,
  mine_id uuid,
  entity_type text,
  entity_id uuid,
  channels ARRAY NOT NULL,
  sla_response_minutes integer,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::alert_status,
  sent_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id),
  CONSTRAINT alerts_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id)
);
CREATE TABLE public.escalation_workflow_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  temporal_workflow_id text,
  workflow_template_id uuid NOT NULL,
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  due_date date NOT NULL,
  current_level integer NOT NULL DEFAULT 0,
  current_assignee_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'active'::escalation_status,
  history jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT escalation_workflow_instances_pkey PRIMARY KEY (id),
  CONSTRAINT escalation_workflow_instances_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT escalation_workflow_instances_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT escalation_workflow_instances_current_assignee_id_fkey FOREIGN KEY (current_assignee_id) REFERENCES public.users(id)
);
CREATE TABLE public.document_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_url text NOT NULL,
  file_name text,
  file_type text,
  file_size_bytes integer,
  document_category USER-DEFINED NOT NULL,
  source_entity_type text,
  source_entity_id uuid,
  mine_id uuid,
  ocr_status USER-DEFINED DEFAULT 'queued'::ocr_status_enum,
  ocr_result_id uuid,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT document_uploads_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT document_uploads_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT fk_du_ocr FOREIGN KEY (ocr_result_id) REFERENCES public.ocr_extraction_results(id)
);
CREATE TABLE public.ocr_extraction_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  ocr_engine text NOT NULL,
  template_matched text,
  raw_text text,
  detected_language text,
  extracted_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  overall_confidence numeric NOT NULL,
  confidence_threshold numeric DEFAULT 0.85,
  verification_status USER-DEFINED NOT NULL DEFAULT 'pending_review'::ocr_verify_status,
  verified_by uuid,
  verified_at timestamp with time zone,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ocr_extraction_results_pkey PRIMARY KEY (id),
  CONSTRAINT ocr_extraction_results_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.document_uploads(id),
  CONSTRAINT ocr_extraction_results_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.mine_risk_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  score numeric NOT NULL,
  risk_level USER-DEFINED NOT NULL,
  contributing_factors jsonb DEFAULT '[]'::jsonb,
  category_scores jsonb DEFAULT '{}'::jsonb,
  trend USER-DEFINED,
  previous_score numeric,
  model_version text NOT NULL,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  next_scheduled_computation timestamp with time zone,
  CONSTRAINT mine_risk_scores_pkey PRIMARY KEY (id),
  CONSTRAINT mine_risk_scores_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT mine_risk_scores_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id)
);
CREATE TABLE public.anomaly_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mine_id uuid NOT NULL,
  subsidiary_id uuid,
  anomaly_type USER-DEFINED NOT NULL,
  data_source text,
  severity USER-DEFINED NOT NULL,
  description text NOT NULL,
  metric_name text,
  expected_value numeric,
  actual_value numeric,
  deviation_pct numeric,
  confidence numeric,
  contributing_data_points jsonb DEFAULT '[]'::jsonb,
  is_acknowledged boolean DEFAULT false,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  model_version text,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT anomaly_flags_pkey PRIMARY KEY (id),
  CONSTRAINT anomaly_flags_mine_id_fkey FOREIGN KEY (mine_id) REFERENCES public.mines(id),
  CONSTRAINT anomaly_flags_subsidiary_id_fkey FOREIGN KEY (subsidiary_id) REFERENCES public.subsidiaries(id),
  CONSTRAINT anomaly_flags_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.users(id)
);
CREATE TABLE public.model_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  observation_id uuid,
  original_ai_category text,
  original_ai_confidence numeric,
  corrected_category text,
  corrected_by uuid,
  corrected_at timestamp with time zone NOT NULL DEFAULT now(),
  used_in_training boolean DEFAULT false,
  CONSTRAINT model_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT model_feedback_observation_id_fkey FOREIGN KEY (observation_id) REFERENCES public.observations(id),
  CONSTRAINT model_feedback_corrected_by_fkey FOREIGN KEY (corrected_by) REFERENCES public.users(id)
);