import { addColumns, createTable, schemaMigrations } from '@nozbe/watermelondb/Schema/migrations';

export const migrations = schemaMigrations({
  migrations: [
    {
      toVersion: 4,
      steps: [
        createTable({
          name: 'notifications',
          columns: [
            { name: 'remote_id', type: 'string' },
            { name: 'type', type: 'string' },
            { name: 'priority', type: 'string' },
            { name: 'title', type: 'string' },
            { name: 'message', type: 'string' },
            { name: 'target_user_id', type: 'string', isOptional: true },
            { name: 'mine_id', type: 'string', isOptional: true },
            { name: 'entity_type', type: 'string', isOptional: true },
            { name: 'entity_id', type: 'string', isOptional: true },
            { name: 'status', type: 'string' },
            { name: 'read_at', type: 'number', isOptional: true },
            { name: 'created_at', type: 'number' },
            { name: 'sync_status', type: 'string' },
          ],
        }),
      ],
    },
    {
      toVersion: 3,
      steps: [
        addColumns({
          table: 'incident_reports',
          columns: [
            { name: 'sync_status', type: 'string' },
            { name: 'incident_type', type: 'string' },
            { name: 'severity', type: 'string' },
            { name: 'ai_suggested_severity', type: 'string', isOptional: true },
            { name: 'ai_suggested_category', type: 'string', isOptional: true },
            { name: 'geo_stamp', type: 'string', isOptional: true },
            { name: 'zone', type: 'string', isOptional: true },
            { name: 'shift', type: 'string', isOptional: true },
            { name: 'persons_involved', type: 'string', isOptional: true },
            { name: 'immediate_actions_taken', type: 'string', isOptional: true },
            { name: 'is_linked_to_accident_register', type: 'boolean' },
            { name: 'corrective_action_id', type: 'string', isOptional: true },
            { name: 'reported_at', type: 'number' },
            { name: 'remote_id', type: 'string', isOptional: true },
            { name: 'local_photo_ids', type: 'string', isOptional: true },
          ],
        }),
        addColumns({
          table: 'attendance_records',
          columns: [
            { name: 'worker_id_card_number', type: 'string' },
            { name: 'worker_name', type: 'string', isOptional: true },
            { name: 'worker_type', type: 'string' },
            { name: 'contractor_id', type: 'string', isOptional: true },
            { name: 'shift', type: 'string' },
            { name: 'check_in_at', type: 'number' },
            { name: 'geo_stamp', type: 'string' },
            { name: 'location_mismatch', type: 'boolean' },
            { name: 'training_expired', type: 'boolean' },
            { name: 'flagged_for_review', type: 'boolean' },
            { name: 'sync_status', type: 'string' },
          ],
        }),
        addColumns({
          table: 'shift_reports',
          columns: [
            { name: 'zone', type: 'string' },
            { name: 'shift', type: 'string' },
            { name: 'report_date', type: 'number' },
            { name: 'workforce_count', type: 'number' },
            { name: 'regular_count', type: 'number' },
            { name: 'contract_count', type: 'number' },
            { name: 'gas_readings', type: 'string' },
            { name: 'shift_observations', type: 'string', isOptional: true },
            { name: 'equipment_status', type: 'string', isOptional: true },
            { name: 'production_coal_tonnes', type: 'number', isOptional: true },
            { name: 'production_ob_cum', type: 'number', isOptional: true },
            { name: 'handover_notes', type: 'string', isOptional: true },
            { name: 'ch4_alert_fired', type: 'boolean' },
            { name: 'geo_stamp', type: 'string' },
            { name: 'sync_status', type: 'string' },
            { name: 'remote_id', type: 'string', isOptional: true },
          ],
        }),
        createTable({
          name: 'safety_observations',
          columns: [
            { name: 'mine_id', type: 'string' },
            { name: 'zone', type: 'string' },
            { name: 'observation_type', type: 'string' },
            { name: 'category', type: 'string', isOptional: true },
            { name: 'description', type: 'string' },
            { name: 'geo_stamp', type: 'string', isOptional: true },
            { name: 'assigned_to_id', type: 'string', isOptional: true },
            { name: 'status', type: 'string' },
            { name: 'corrected_at', type: 'number', isOptional: true },
            { name: 'observed_by', type: 'string' },
            { name: 'observed_at', type: 'number' },
            { name: 'sync_status', type: 'string' },
            { name: 'remote_id', type: 'string', isOptional: true },
            { name: 'local_photo_id', type: 'string', isOptional: true },
          ],
        }),
        createTable({
          name: 'contract_workers',
          columns: [
            { name: 'remote_id', type: 'string' },
            { name: 'contractor_id', type: 'string' },
            { name: 'name', type: 'string' },
            { name: 'worker_id_card_number', type: 'string' },
            { name: 'training_certificates', type: 'string' },
            { name: 'is_active', type: 'boolean' },
            { name: 'synced_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'media_attachments',
          columns: [
            { name: 'parent_type', type: 'string' },
            { name: 'parent_id', type: 'string' },
            { name: 'media_type', type: 'string' },
            { name: 'local_file_path', type: 'string' },
            { name: 'file_url', type: 'string', isOptional: true },
            { name: 'sync_status', type: 'string' },
            { name: 'remote_id', type: 'string', isOptional: true },
            { name: 'captured_by', type: 'string' },
            { name: 'created_at', type: 'number' },
          ],
        }),
      ],
    },
    {
      toVersion: 2,
      steps: [
        addColumns({
          table: 'inspections',
          columns: [
            { name: 'inspection_type', type: 'string' },
            { name: 'checklist_template_id', type: 'string' },
            { name: 'conducted_by', type: 'string' },
            { name: 'geo_stamp_start', type: 'string', isOptional: true },
            { name: 'geo_stamp_end', type: 'string', isOptional: true },
            { name: 'started_at', type: 'number', isOptional: true },
            { name: 'completed_at', type: 'number', isOptional: true },
            { name: 'submitted_at', type: 'number', isOptional: true },
            { name: 'signed_at', type: 'number', isOptional: true },
            { name: 'sync_status', type: 'string' },
            { name: 'current_section', type: 'number' },
            { name: 'overall_remarks', type: 'string', isOptional: true },
            { name: 'observation_count', type: 'number' },
            { name: 'violation_count', type: 'number' },
            { name: 'remote_id', type: 'string', isOptional: true },
          ],
        }),
        addColumns({
          table: 'observations',
          columns: [
            { name: 'checklist_item_id', type: 'string', isOptional: true },
            { name: 'statute_ref', type: 'string', isOptional: true },
            { name: 'response_type', type: 'string', isOptional: true },
            { name: 'photo_uris', type: 'string', isOptional: true },
            { name: 'sub_zone', type: 'string', isOptional: true },
            { name: 'gas_readings', type: 'string', isOptional: true },
            { name: 'sync_status', type: 'string' },
            { name: 'remote_id', type: 'string', isOptional: true },
            { name: 'updated_at', type: 'number' },
          ],
        }),
        createTable({
          name: 'checklist_templates',
          columns: [
            { name: 'remote_id', type: 'string' },
            { name: 'name', type: 'string' },
            { name: 'inspection_type', type: 'string' },
            { name: 'regulation_ref', type: 'string', isOptional: true },
            { name: 'checklist_items', type: 'string' },
            { name: 'version', type: 'number' },
            { name: 'is_active', type: 'boolean' },
            { name: 'synced_at', type: 'number' },
          ],
        }),
      ],
    },
  ],
});
